// Code generated by scripts/api-contract-digest.sh; DO NOT EDIT.

/// Identity of the api/openapi.yaml this client was built from.
public enum APIContract {
    /// "sha256:" plus the lowercase hex SHA-256 of the spec's exact bytes.
    /// The client compares this with the daemon's reported digest on
    /// GET /health to diagnose a client/daemon contract skew.
    public static let digest = "sha256:2c4bf84c9c54fce0b08029566dc8c529f558fdb1dd8894347ebcb05ed17d3610"
}
