// Code generated by scripts/api-contract-digest.sh; DO NOT EDIT.

/// Identity of the api/openapi.yaml this client was built from.
public enum APIContract {
    /// "sha256:" plus the lowercase hex SHA-256 of the spec's exact bytes.
    /// The client compares this with the daemon's reported digest on
    /// GET /health to diagnose a client/daemon contract skew.
    public static let digest = "sha256:25a41da9f001e8d1de8fc93e5a7f090d7c4402275855acfad2704a8e9c885c52"
}
