// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
/// **Provisional.** This schema is provisional until exercised by real
/// clients (plan §11 Wave 0; the decision record lives in
/// docs/history/decisions.md, decision 21: "API provisional until
/// exercised"). It covers plan §5.14's synchronization surface: the
/// canonical bootstrap snapshot, the attention/runs/conversations read
/// surfaces, ClientCommand submission, and digest-addressed attachment
/// upload. Any change to this document is treated as a migration
/// (api/README.md).
///
/// The daemon is sole authority; client databases are disposable read
/// caches. Every schema mirrors its `daemon/internal/domain` type
/// field-for-field: every field is always present on the wire (the daemon
/// marshals without omission), so each object lists all its properties as
/// required and marks Go pointer fields nullable. Timestamps are RFC3339
/// UTC `date-time` strings; durations are int64 nanoseconds; identifiers
/// and digests are opaque non-empty strings.
///
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// Process liveness, version, and start time
    ///
    /// Answers only "is the daemon process up, which build, since when."
    /// Supervisors and the external liveness probe poll it (plan §5.2);
    /// the operator client uses `version` for skew detection and
    /// `started_at` for restart visibility (a start time that keeps
    /// moving under a supervisor is crash-loop evidence). The response
    /// deliberately carries no operational state: unattended-admission
    /// stops, `system_health` items, and everything else requiring
    /// judgment stay on the authenticated surfaces (plan §4), so this
    /// route widens what an unpaired caller learns by nothing beyond
    /// liveness, version, and start time.
    ///
    ///
    /// - Remark: HTTP `GET /health`.
    /// - Remark: Generated from `#/paths//health/get(getHealth)`.
    public func getHealth(_ input: Operations.getHealth.Input) async throws -> Operations.getHealth.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getHealth.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/health",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getHealth.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.HealthStatus.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// One canonical snapshot of every synchronized resource
    ///
    /// Returns one canonical snapshot produced in a single daemon read
    /// transaction (plan §5.14). The response carries the server's
    /// `sync_epoch` and `revision`; a client replaces its whole cache with
    /// this snapshot and records `revision` as its
    /// `last_full_snapshot_revision`. A partial fetch (any other read
    /// endpoint) never advances the whole cache: clients track
    /// `last_full_snapshot_revision` and `highest_observed_server_revision`
    /// separately, and a revision gap triggers a new bootstrap or a refetch
    /// of all potentially affected resources. A changed `sync_epoch` (a
    /// daemon restore) forces cache discard and a fresh bootstrap.
    ///
    ///
    /// - Remark: HTTP `GET /sync/bootstrap`.
    /// - Remark: Generated from `#/paths//sync/bootstrap/get(getSyncBootstrap)`.
    public func getSyncBootstrap(_ input: Operations.getSyncBootstrap.Input) async throws -> Operations.getSyncBootstrap.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getSyncBootstrap.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/sync/bootstrap",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getSyncBootstrap.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.BootstrapSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// The current server revision and sync epoch
    ///
    /// The periodic revision heartbeat that catches lost invalidations
    /// (plan §5.14; sync test 11): a client polls this cheap read and
    /// compares `revision` against its
    /// `highest_observed_server_revision`. A gap means invalidations were
    /// missed, so the client refetches affected resources or bootstraps;
    /// it never marks the whole cache current from this response (only a
    /// bootstrap advances `last_full_snapshot_revision`). A changed
    /// `sync_epoch` (a daemon restore) forces cache discard and a fresh
    /// bootstrap.
    ///
    ///
    /// - Remark: HTTP `GET /sync/revision`.
    /// - Remark: Generated from `#/paths//sync/revision/get(getSyncRevision)`.
    public func getSyncRevision(_ input: Operations.getSyncRevision.Input) async throws -> Operations.getSyncRevision.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getSyncRevision.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/sync/revision",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getSyncRevision.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ServerRevision.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// List attention items
    ///
    /// Lists attention items as individual resource snapshots. A partial fetch: the result updates only the entities it carries and never marks the whole cache current (plan §5.14).
    ///
    ///
    /// - Remark: HTTP `GET /attention/items`.
    /// - Remark: Generated from `#/paths//attention/items/get(listAttentionItems)`.
    public func listAttentionItems(_ input: Operations.listAttentionItems.Input) async throws -> Operations.listAttentionItems.Output {
        try await client.send(
            input: input,
            forOperation: Operations.listAttentionItems.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.listAttentionItems.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.AttentionItemSnapshot].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Get one attention item
    ///
    /// Returns the item's current canonical state as a resource snapshot. A late notification deep-links here and exposes no stale action (plan §5.14 sync test 9). The notification's deep link targets this operation with channel and attempt query parameters identifying the delivery attempt; this GET stays side-effect-free, and the client reports the opened receipt separately via reportDeliveryOpened.
    ///
    ///
    /// - Remark: HTTP `GET /attention/items/{item_id}`.
    /// - Remark: Generated from `#/paths//attention/items/{item_id}/get(getAttentionItem)`.
    public func getAttentionItem(_ input: Operations.getAttentionItem.Input) async throws -> Operations.getAttentionItem.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getAttentionItem.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items/{}",
                    parameters: [
                        input.path.item_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getAttentionItem.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AttentionItemSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Get authenticated run-proposal facts
    ///
    /// Returns the exact digest-bound run-proposal facts rendered by a run_proposal item. The daemon reconstructs the private proposal ledger, re-resolves the opaque work-unit handle through its durable declaration and current policy, and returns only bounded review facts. The version tuple lets the client prove the facts and card were read from the same item state. Active snoozes remain hidden as 404.
    ///
    ///
    /// - Remark: HTTP `GET /attention/items/{item_id}/run-proposal`.
    /// - Remark: Generated from `#/paths//attention/items/{item_id}/run-proposal/get(getRunProposalFacts)`.
    public func getRunProposalFacts(_ input: Operations.getRunProposalFacts.Input) async throws -> Operations.getRunProposalFacts.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getRunProposalFacts.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items/{}/run-proposal",
                    parameters: [
                        input.path.item_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getRunProposalFacts.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.RunProposalFactsSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// List an item's delivery attempts
    ///
    /// Lists the item's per-channel, per-attempt delivery records (plan §4). Delivery rows are created and advanced by the daemon's delivery pipeline; the single client write is the opened receipt (reportDeliveryOpened), which advances an existing attempt and never creates one.
    ///
    ///
    /// - Remark: HTTP `GET /attention/items/{item_id}/deliveries`.
    /// - Remark: Generated from `#/paths//attention/items/{item_id}/deliveries/get(listAttentionItemDeliveries)`.
    public func listAttentionItemDeliveries(_ input: Operations.listAttentionItemDeliveries.Input) async throws -> Operations.listAttentionItemDeliveries.Output {
        try await client.send(
            input: input,
            forOperation: Operations.listAttentionItemDeliveries.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items/{}/deliveries",
                    parameters: [
                        input.path.item_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.listAttentionItemDeliveries.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.AttentionDeliverySnapshot].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Report a delivery attempt as opened
    ///
    /// Records the authenticated device's opened receipt on one delivery
    /// attempt: the row advances to `opened` with a daemon-stamped
    /// `opened_at`, and the item's timing aggregates re-derive in the
    /// same transaction (plan §4). The receipt carries no request body:
    /// the attempt is fully identified by the path, and the device comes
    /// solely from the bearer credential — a device can open only its
    /// own deliveries, and another device's attempt is a plain 404.
    /// Idempotent by the attempt's identity: replaying an already-opened
    /// receipt returns the recorded snapshot without moving the server
    /// revision (the PUT converges on the one recorded receipt, like the
    /// digest-addressed attachment upload). The item's lifecycle status
    /// is deliberately not a gate: a late receipt for a resolved item is
    /// honest telemetry, and its canonical rendering is the deep-link
    /// GET's concern (plan §5.14 sync test 9). Deliberately not a
    /// ClientCommand: a receipt is monotonic telemetry about the past,
    /// not a judgment on canonical state, and an expected_entity_version
    /// precondition would wrongly reject legitimate receipts as the
    /// delivery row advances from submitted to channel_accepted.
    ///
    ///
    /// - Remark: HTTP `PUT /attention/items/{item_id}/deliveries/{channel}/{attempt}/opened`.
    /// - Remark: Generated from `#/paths//attention/items/{item_id}/deliveries/{channel}/{attempt}/opened/put(reportDeliveryOpened)`.
    public func reportDeliveryOpened(_ input: Operations.reportDeliveryOpened.Input) async throws -> Operations.reportDeliveryOpened.Output {
        try await client.send(
            input: input,
            forOperation: Operations.reportDeliveryOpened.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items/{}/deliveries/{}/{}/opened",
                    parameters: [
                        input.path.item_id,
                        input.path.channel,
                        input.path.attempt
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.reportDeliveryOpened.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AttentionDeliverySnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 400:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.reportDeliveryOpened.Output.BadRequest.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .badRequest(.init(body: body))
                case 403:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.reportDeliveryOpened.Output.Forbidden.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .forbidden(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// List runs
    ///
    /// Lists runs as resource snapshots. Each run embeds its stages and attempts (the run is the aggregate root). A partial fetch; it never marks the whole cache current (plan §5.14).
    ///
    ///
    /// - Remark: HTTP `GET /runs`.
    /// - Remark: Generated from `#/paths//runs/get(listRuns)`.
    public func listRuns(_ input: Operations.listRuns.Input) async throws -> Operations.listRuns.Output {
        try await client.send(
            input: input,
            forOperation: Operations.listRuns.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/runs",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.listRuns.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.RunSnapshot].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Get one run
    ///
    /// Returns the run aggregate (stages and attempts embedded) as a resource snapshot.
    ///
    /// - Remark: HTTP `GET /runs/{run_id}`.
    /// - Remark: Generated from `#/paths//runs/{run_id}/get(getRun)`.
    public func getRun(_ input: Operations.getRun.Input) async throws -> Operations.getRun.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getRun.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/runs/{}",
                    parameters: [
                        input.path.run_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getRun.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.RunSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Get one run timeline
    ///
    /// Returns the daemon-derived milestone, hold, and invocation-observation timeline for one run. The snapshot is computed in one store read and carries the revision that bounds every fact. A partial fetch; it never marks the whole cache current (plan §5.14).
    ///
    ///
    /// - Remark: HTTP `GET /runs/{run_id}/timeline`.
    /// - Remark: Generated from `#/paths//runs/{run_id}/timeline/get(getRunTimeline)`.
    public func getRunTimeline(_ input: Operations.getRunTimeline.Input) async throws -> Operations.getRunTimeline.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getRunTimeline.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/runs/{}/timeline",
                    parameters: [
                        input.path.run_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getRunTimeline.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.RunTimeline.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// List durable schedules
    ///
    /// Lists the durable scheduler's synchronized schedule aggregates (plan §5.16). A partial fetch; it never marks the whole cache current (plan §5.14).
    ///
    ///
    /// - Remark: HTTP `GET /schedules`.
    /// - Remark: Generated from `#/paths//schedules/get(listSchedules)`.
    public func listSchedules(_ input: Operations.listSchedules.Input) async throws -> Operations.listSchedules.Output {
        try await client.send(
            input: input,
            forOperation: Operations.listSchedules.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/schedules",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.listSchedules.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            [Components.Schemas.ScheduleSnapshot].self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Get one conversation as a whole snapshot
    ///
    /// Phase 1 conversation sync is whole-snapshot per conversation (plan §5.14): the response carries the complete ordered message thread (daemon-assigned contiguous sequence numbers), not a delta. Messages are immutable; corrections are new messages. Attachments are not inlined; they are fetched by digest.
    ///
    ///
    /// - Remark: HTTP `GET /conversations/{conversation_id}`.
    /// - Remark: Generated from `#/paths//conversations/{conversation_id}/get(getConversation)`.
    public func getConversation(_ input: Operations.getConversation.Input) async throws -> Operations.getConversation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getConversation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/conversations/{}",
                    parameters: [
                        input.path.conversation_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getConversation.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ConversationSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Derive the authenticated device's action surface for an item
    ///
    /// Returns the DecisionActionSurface the authenticated device is offered
    /// for the item's current decision surface (plan §5.14, §8): the
    /// intersection of the item's requested decisions with the device's
    /// registered capability contract. Deliberately not a ClientCommand, like
    /// reportDeliveryOpened: the surface is comprehension telemetry, derived
    /// and persisted on first sight, and it never widens the item's actions.
    /// The device comes solely from the bearer credential. A device that has
    /// registered no capability contract earns 409; a missing item is 404.
    ///
    ///
    /// - Remark: HTTP `GET /attention/items/{item_id}/action-surface`.
    /// - Remark: Generated from `#/paths//attention/items/{item_id}/action-surface/get(getActionSurface)`.
    public func getActionSurface(_ input: Operations.getActionSurface.Input) async throws -> Operations.getActionSurface.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getActionSurface.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attention/items/{}/action-surface",
                    parameters: [
                        input.path.item_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getActionSurface.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DecisionActionSurface.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getActionSurface.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Submit a client command
    ///
    /// The single mutation surface for judgment-bearing decisions on
    /// synchronized domain state: every such client mutation is a
    /// ClientCommand (plan §5.14); only the credential control surface
    /// (pairing, revocation), attachment upload, and the delivery opened
    /// receipt (monotonic telemetry, reportDeliveryOpened) sit outside
    /// it. Submission is idempotent by
    /// `command_id`: the daemon records each command's result in the same
    /// transaction that applies it, and a retry of an already-committed
    /// `command_id` returns the original recorded result without applying
    /// anything again (a lost HTTP response is recovered by retrying, sync
    /// test 4). Optimistic concurrency: a command prepared against a stale
    /// `expected_entity_version` (or stale bindings) is rejected with the
    /// replacement state and no side effect (sync test 2).
    ///
    ///
    /// - Remark: HTTP `POST /commands`.
    /// - Remark: Generated from `#/paths//commands/post(submitCommand)`.
    public func submitCommand(_ input: Operations.submitCommand.Input) async throws -> Operations.submitCommand.Output {
        try await client.send(
            input: input,
            forOperation: Operations.submitCommand.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/commands",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.submitCommand.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.CommandResult.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 409:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.submitCommand.Output.Conflict.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.StaleVersionRejection.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .conflict(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Exchange a pairing code for a device credential
    ///
    /// Exchanges a short-lived pairing code (displayed on the daemon host,
    /// plan §5.14) for a new device, its bearer token, and the device's
    /// ntfy subscription. The token and subscription appear only in this
    /// response and are never exposed through Device or the sync surfaces;
    /// the daemon stores only the token's digest. Consumption is
    /// single-winner: simultaneous attempts with one code yield one device
    /// (sync test 14), and an expired or consumed code creates nothing
    /// (sync test 13).
    ///
    ///
    /// - Remark: HTTP `POST /pairing`.
    /// - Remark: Generated from `#/paths//pairing/post(pairDevice)`.
    public func pairDevice(_ input: Operations.pairDevice.Input) async throws -> Operations.pairDevice.Output {
        try await client.send(
            input: input,
            forOperation: Operations.pairDevice.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/pairing",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.pairDevice.Output.Created.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PairingGrant.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .created(.init(body: body))
                case 403:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.pairDevice.Output.Forbidden.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .forbidden(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Preview what a pairing code would join
    ///
    /// Reports, for a live pairing code, the operational facts the pairing
    /// screen shows before the code is redeemed (plan §5.14): which host
    /// the device is about to join, when the code expires, how the client
    /// is reaching the daemon, and what authority the new device gets.
    /// A preview never consumes the code, never creates a device, and
    /// never moves the server revision; the same code then pairs through
    /// POST /pairing, whose grant carries the same facts. The response
    /// holds no credential, key material, or §5.9 host identity: the host
    /// name is a display fact only.
    ///
    ///
    /// - Remark: HTTP `POST /pairing/preview`.
    /// - Remark: Generated from `#/paths//pairing/preview/post(previewPairing)`.
    public func previewPairing(_ input: Operations.previewPairing.Input) async throws -> Operations.previewPairing.Output {
        try await client.send(
            input: input,
            forOperation: Operations.previewPairing.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/pairing/preview",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.previewPairing.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.PairingFacts.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 403:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.previewPairing.Output.Forbidden.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .forbidden(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Revoke a paired device
    ///
    /// Revokes the device's credential (plan §5.14): a revoked device
    /// cannot submit a previously prepared, uncommitted command (sync test
    /// 15), while a committed command's recorded result stays retrievable
    /// and a retry produces no new side effect (sync test 16). Revocation
    /// stops future access only; it cannot delete content the device
    /// already cached (no remote wipe). Terminal and idempotent: revoking
    /// an already-revoked device returns the same recorded snapshot.
    /// Deliberately not a ClientCommand: revocation is the credential
    /// control surface (it invalidates what commands authenticate with,
    /// and must not depend on the revoked device's cooperation), not a
    /// decision on an attention item.
    ///
    ///
    /// - Remark: HTTP `POST /devices/{device_id}/revoke`.
    /// - Remark: Generated from `#/paths//devices/{device_id}/revoke/post(revokeDevice)`.
    public func revokeDevice(_ input: Operations.revokeDevice.Input) async throws -> Operations.revokeDevice.Output {
        try await client.send(
            input: input,
            forOperation: Operations.revokeDevice.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/devices/{}/revoke",
                    parameters: [
                        input.path.device_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.revokeDevice.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeviceSnapshot.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Register the device's action capability contract
    ///
    /// Records the set of decision actions the authenticated device's app
    /// build can present and submit (plan §5.14, §8), so the daemon can derive
    /// the device's action surface for each item. Deliberately not a
    /// ClientCommand: it is comprehension telemetry, not a decision on an
    /// attention item. The path device must equal the bearer credential's
    /// device (else a plain 404, the deliveries posture): a device registers
    /// only its own contract. Idempotent by content: re-registering the same
    /// action set returns the same contract without moving the server
    /// revision.
    ///
    ///
    /// - Remark: HTTP `PUT /devices/{device_id}/capability-contract`.
    /// - Remark: Generated from `#/paths//devices/{device_id}/capability-contract/put(registerCapabilityContract)`.
    public func registerCapabilityContract(_ input: Operations.registerCapabilityContract.Input) async throws -> Operations.registerCapabilityContract.Output {
        try await client.send(
            input: input,
            forOperation: Operations.registerCapabilityContract.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/devices/{}/capability-contract",
                    parameters: [
                        input.path.device_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.registerCapabilityContract.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ClientCapabilityContract.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 400:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.registerCapabilityContract.Output.BadRequest.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .badRequest(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Fetch an attachment by content digest
    ///
    /// Digest-addressed read: returns the stored bytes the path digest names. Clients render image attachments directly from the artifact store by digest (plan §4), and conversation attachments are never inlined (plan §5.14), so this is the read path for the bytes an item's evidence_snapshot, agent_claims, and artifact_digests and a message's attachments reference. Content is immutable per digest.
    ///
    ///
    /// - Remark: HTTP `GET /attachments/{digest}`.
    /// - Remark: Generated from `#/paths//attachments/{digest}/get(getAttachment)`.
    public func getAttachment(_ input: Operations.getAttachment.Input) async throws -> Operations.getAttachment.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getAttachment.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attachments/{}",
                    parameters: [
                        input.path.digest
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getAttachment.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/octet-stream"
                        ]
                    )
                    switch chosenContentType {
                    case "application/octet-stream":
                        body = try converter.getResponseBodyAsBinary(
                            OpenAPIRuntime.HTTPBody.self,
                            from: responseBody,
                            transforming: { value in
                                .binary(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Upload an attachment by content digest
    ///
    /// Digest-addressed upload (plan §5.14): the path digest names the
    /// content, and the daemon verifies the body hashes to it. A retried
    /// upload converges on one artifact by digest (sync test 10): re-PUT of
    /// an already-stored digest is a no-op that returns the same receipt.
    /// The daemon treats attachment bytes as opaque blobs (magic-byte,
    /// type, and size validation only; plan §5.15); rendering happens only
    /// in clients.
    ///
    ///
    /// - Remark: HTTP `PUT /attachments/{digest}`.
    /// - Remark: Generated from `#/paths//attachments/{digest}/put(uploadAttachment)`.
    public func uploadAttachment(_ input: Operations.uploadAttachment.Input) async throws -> Operations.uploadAttachment.Output {
        try await client.send(
            input: input,
            forOperation: Operations.uploadAttachment.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/attachments/{}",
                    parameters: [
                        input.path.digest
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .binary(value):
                    body = try converter.setRequiredRequestBodyAsBinary(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/octet-stream"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.uploadAttachment.Output.Created.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AttachmentReceipt.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .created(.init(body: body))
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.uploadAttachment.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.AttachmentReceipt.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 422:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.uploadAttachment.Output.UnprocessableContent.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .unprocessableContent(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Record one comprehension event
    ///
    /// Ingests one typed decision-path event (plan §8). Deliberately not a
    /// ClientCommand, like reportDeliveryOpened: it records a fact, makes no
    /// judgment, and has no version precondition. Recording never advances the
    /// server revision. The device is the bearer credential's and the event_id
    /// is the path idempotency key, so the body carries neither; received_at is
    /// daemon-stamped. Idempotent by (device, event_id): replaying returns the
    /// recorded event unchanged. The action-bearing kinds (action_taken,
    /// recommendation_override) must reference an accepted command that belongs
    /// to the device and item and carries the same action surface digest.
    ///
    ///
    /// - Remark: HTTP `PUT /telemetry/comprehension/{event_id}`.
    /// - Remark: Generated from `#/paths//telemetry/comprehension/{event_id}/put(recordComprehensionEvent)`.
    public func recordComprehensionEvent(_ input: Operations.recordComprehensionEvent.Input) async throws -> Operations.recordComprehensionEvent.Output {
        try await client.send(
            input: input,
            forOperation: Operations.recordComprehensionEvent.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/telemetry/comprehension/{}",
                    parameters: [
                        input.path.event_id
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.recordComprehensionEvent.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ComprehensionEvent.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                case 400:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.recordComprehensionEvent.Output.BadRequest.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .badRequest(.init(body: body))
                case 403:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.recordComprehensionEvent.Output.Forbidden.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .forbidden(.init(body: body))
                case 404:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Components.Responses.NotFound.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas._Error.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .notFound(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
