#!/usr/bin/env bash
# api-contract-digest.sh — the single source of the API contract identity.
#
# The contract digest is "sha256:" plus the lowercase hex SHA-256 of the
# exact bytes of api/openapi.yaml. It is written into two generated,
# compiled-in constants so neither the daemon nor the Swift client can
# drift from the spec:
#   daemon/internal/signet/contract_digest.go   (const APIContractDigest)
#   app/Sources/FreesideAPI/ContractDigest.swift (APIContract.digest)
#
# The daemon reports the constant on GET /health; the client compares the
# daemon's reported digest with its own compiled-in constant to diagnose a
# client/daemon contract skew instead of a silent sync failure (#1265).
#
# Usage:
#   api-contract-digest.sh            print the digest
#   api-contract-digest.sh --write    (re)write both generated constants
#   api-contract-digest.sh --check    fail if either generated constant is
#                                     stale, naming the file and the fix
#
# The `api` component's `digest` step (scripts/check.sh) runs --check, as
# does app/scripts/generate-api-client.sh's drift list, so CI fails when a
# spec change forgets to regenerate the constants.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
SPEC="$ROOT/api/openapi.yaml"
GO_FILE="$ROOT/daemon/internal/signet/contract_digest.go"
SWIFT_FILE="$ROOT/app/Sources/FreesideAPI/ContractDigest.swift"

sha256_hex() { # <file>; prints the lowercase hex SHA-256 of the file
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    echo "api-contract-digest.sh: no sha256sum or shasum found" >&2
    exit 1
  fi
}

digest() { printf 'sha256:%s' "$(sha256_hex "$SPEC")"; }

go_contents() { # <digest>
  cat <<EOF
// Code generated by scripts/api-contract-digest.sh; DO NOT EDIT.

package signet

// APIContractDigest identifies the api/openapi.yaml this daemon was built
// from: "sha256:" plus the lowercase hex SHA-256 of the spec's exact
// bytes. The daemon reports it on GET /health so a client can detect a
// contract skew. Regenerate with scripts/api-contract-digest.sh --write.
const APIContractDigest = "$1"
EOF
}

swift_contents() { # <digest>
  cat <<EOF
// Code generated by scripts/api-contract-digest.sh; DO NOT EDIT.

/// Identity of the api/openapi.yaml this client was built from.
public enum APIContract {
    /// "sha256:" plus the lowercase hex SHA-256 of the spec's exact bytes.
    /// The client compares this with the daemon's reported digest on
    /// GET /health to diagnose a client/daemon contract skew.
    public static let digest = "$1"
}
EOF
}

write() {
  local d
  d=$(digest)
  go_contents "$d" >"$GO_FILE"
  swift_contents "$d" >"$SWIFT_FILE"
  echo "wrote $GO_FILE and $SWIFT_FILE ($d)" >&2
}

check() {
  local d stale=0
  d=$(digest)
  if ! diff -u <(cat "$GO_FILE" 2>/dev/null) <(go_contents "$d") >/dev/null 2>&1; then
    echo "stale: $GO_FILE" >&2
    stale=1
  fi
  if ! diff -u <(cat "$SWIFT_FILE" 2>/dev/null) <(swift_contents "$d") >/dev/null 2>&1; then
    echo "stale: $SWIFT_FILE" >&2
    stale=1
  fi
  if [ "$stale" -ne 0 ]; then
    echo "regenerate with: bash scripts/api-contract-digest.sh --write" >&2
    exit 1
  fi
  echo "contract digest constants match api/openapi.yaml ($d)" >&2
}

case "${1-}" in
  "") digest ;;
  --write) write ;;
  --check) check ;;
  *)
    echo "usage: $(basename "$0") [--write|--check]" >&2
    exit 2
    ;;
esac
