// Code generated by scripts/api-contract-digest.sh; DO NOT EDIT.

package signet

// APIContractDigest identifies the api/openapi.yaml this daemon was built
// from: "sha256:" plus the lowercase hex SHA-256 of the spec's exact
// bytes. The daemon reports it on GET /health so a client can detect a
// contract skew. Regenerate with scripts/api-contract-digest.sh --write.
const APIContractDigest = "sha256:17b45a95fd6e9ad572d4b60b58034a14370ed41f8342392be8f59a8e03f32a58"
